---
title: "Lab 9, Part 2: Stringr package practice"
author: "Sydney Mayes"
date: "2023-03-11"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(tidyverse)
```

## Useful functions in `stringr` (which is in tidyverse)

### Detect a pattern with `stringr::str_detect()`
```{r}
### make a practice vector
vec <- c('  A Unicorn   Fish',
         ' add  cornmeal',
         '   French FRIES',
         '   acorn squash123  ')
### try detecting some patterns
str_detect(vec, pattern = 'corn')
# will return true or false for each string
str_detect(vec, pattern = 'fish') # case sensitive!
str_detect(vec, pattern = 'Fish')
str_to_lower(vec) # converts all to lowercase
str_to_upper(vec)
str_to_title(vec)
str_to_sentence(vec)

str_to_lower(vec) %>% 
  str_detect(pattern = 'fish')

### let's extract some strings
str_extract(vec, pattern = 'corn') # NA if no corn in string. 

str_extract(vec, pattern = '[a-z]') #pattern I am looking for is in a-z lowercase. it pulls out the first letter of each string that matches these requirements. 
str_extract(vec, pattern = '[A-Z]') 

str_extract(vec, pattern = '[0-9]') %>% as.numeric() # if we want it to return not as a string

str_extract(vec, pattern = '[a-z]+') # with the plus sign we get the whole word after the first set of consecutive occurences of the pattern
str_extract_all(vec, pattern = '[a-z]+') # extract all with the pattern

str_extract_all(vec, pattern = '[0-9]+') %>% as.numeric()


```

```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = 'walk')) #filter by if name has 'walk' in it

str_replace(vec, pattern = 'corn', replacement = 'COOL') 
str_replace(vec, pattern = 'a', replacement = 'ZZZ') # takes first instance of 'a' and replaces it but not the other instances
str_replace_all(vec, pattern = 'a', replacement = 'ZZZ') # this however replaces all

sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = 'Sky', replacement = 'TORNADO')) # Now we see Luke TORNADOwalker, etc. lol

sw_wacky <- starwars %>% 
  mutate(name2 = str_replace(name, pattern = '(w|W)b?a.+' , replacement = 'WACKY')) %>% 
  # means look for a lowercase w OR an uppercase W, that is followed by a b or no b. '.' means match with any characters after
  select(name, name2) 
```

```{r}
vec
str_trim(vec) # gets rid of the extra white space on the ends
str_squish(vec) # gets rid of the interior white space as well!
```

### Let's use these in combination
```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, 'Darth')) %>% 
  mutate(name = str_replace(name, pattern = 'Darth', replacement = 'Llama')) %>% # result is Llama Vader lol
  mutate(name = str_to_lower(name))
```

